### PR TITLE
Resolves #46. Aggregation options.

### LINKED ISSUE #46: As a GUI user, I can choose aggregation while looking at the chart
Perhaps a dropdown menu like the current limit and since? 

For the user to choose an aggregation, the "since" dropdown must be chosen. This is because the backend database cannot aggregate on the data without a start time. So the aggregation dropdown should be disabled unless the user has chosen a "since" time. 

The options for aggregation should be an integer and a duration (so maybe a dropdown won't work?). Ideally user will input an integer like `3` and choose a duration from the following: seconds, minutes, hours, days, weeks. 

The actual call to the server can just append the aggretation parameter to the URL like this:

    /_data/sensor/power/Mini+Fridge?since=1455042385

Plus 1 hour aggregation:

    /_data/sensor/power/Mini+Fridge?since=1455042385&aggregate=1h

### PR DESCRIPTION
**Pull request by jefffohl**
Addresses #46 and #38.

### CODE REVIEW

**Comment by jefffohl** [comment]
@rhyolight - do you want to review? This is the aggregation feature.

**Comment by rhyolight** [comment]
Yes, standby...

**Comment by rhyolight** [comment]
Something is wrong, possibly on my end, I'll get back to you when I have time to work on it.

**Comment by rhyolight** [comment]
@jefffohl Works great!

**Pull request merged**
